jwt.secret: javainuse
#jwt.timetoken:  18000 
jwt.timetoken:  6000
spring:
  datasource: 
    url : jdbc:mysql://localhost/managerlab
    username : root
    password : 123456
    platform : mysql
    driver-class-name : com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql : false
    hibernate: 
      ddl-auto : none 
      naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl