server:
  port: ${PORT:8080}
jwt.secret: VmVuZXNhSVQhQDIwMjBTZWNyZXRrZXlTcGFBbmRHeW1KV1Q=
#jwt.timetoken:  18000 
jwt.timetoken:  6000
spring:
  datasource: 
    url : jdbc:mysql://127.0.0.1:3306/managerlab
    username : root
    password : 123456
    platform : mysql
    driver-class-name : com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql : true
    hibernate: 
      ddl-auto : none
      naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  mail:
    host : smtp.gmail.com
    port : 587
    properties.mail.smtp :
                    auth : true
                    starttls.enable : true
                          
  servlet.multipart:
          max-file-size : 500MB
          max-request-size : 500MB

aws:
  access:
    key:
      id : AKIAV65AQVKMJXFRXRNJ
      secret : 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

  region : ap-southeast-1
  s3:
    audio:
       bucket : thuanlm-fin